# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10
#[[main]]
#  name = "About (Deprecated)"
#  url = "/about_deprecated"
#  identifier = "about_deprecated"
#  weight = 11
[[main]]
  name = "News"
  url = "/news/"
  weight = 20
[[main]]
  name = "Documentation"
  url = "/docs/"
  weight = 30
[[main]]
  name = "Tutorials"
  url = "/tutorials/"
  weight = 40
[[main]]
  identifier = "Download"
  name = "Download"
  url = "/download/"
  weight = 50
[[main]]
  identifier = "Commercial"
  name = "Commercial"
  url = "/commercial/"
  weight = 60
[[main]]
  name = "Community"
  url = "/community/"
  weight = 70


[[footer]]
  name = "Eclipse MOSAIC"
  identifier = "mosaic"
  weight = 1
    [[footer]]
      name = "Download Eclipse MOSAIC"
      url = "/download/"
      identifier = "download"
      parent = "mosaic"
      weight = 1
    [[footer]]
      name = "Documentation"
      url = "/docs/"
      identifier = "documentation"
      parent = "mosaic"
      weight = 2
    [[footer]]
      name = "Tutorials"
      url = "/tutorials/"
      identifier = "tutorials"
      parent = "mosaic"
      weight = 3
    [[footer]]
      name = "License"
      url = "/about/#license"
      identifier = "license"
      parent = "mosaic"
      weight = 4
    [[footer]]
      name = "Projects"
      url = "/community/#projects"
      identifier = "projects"
      parent = "mosaic"
      weight = 5
    [[footer]]
      name = "Publications"
      url = "/publications/"
      identifier = "publications"
      parent = "mosaic"
      weight = 6
[[footer]]
  name = "Community"
  identifier = "community"
  weight = 2
    [[footer]]
      name = "Eclipse MOSAIC Community"
      url = "/community/"
      identifier = "mosaic-community"
      parent = "community"
      weight = 1
    [[footer]]
      name = "How to contribute"
      url = "/contribution/"
      identifier = "contribution"
      parent = "community"
      weight = 2
    [[footer]]
      name = "Github"
      url = "https://github.com/eclipse/mosaic"
      identifier = "github"
      parent = "community"
      weight = 3
    [[footer]]
      name = "Contact & Mailing list"
      url = "/get_in_contact/"
      identifier = "get-in-contact"
      parent = "community"
      weight = 4
[[footer]]
  name = "Eclipse Foundation"
  identifier = "eclipse"
  weight = 3
    [[footer]]
      name = "About Eclipse Foundation"
      url = "https://www.eclipse.org/"
      identifier = "logo"
      parent = "eclipse"
      weight = 1
    [[footer]]
      name = "Privacy Policy"
      url = "https://www.eclipse.org/legal/privacy.php"
      identifier = "privacy-policy"
      parent = "eclipse"
      weight = 2
    [[footer]]
      name = "Website terms of use"
      url = "https://www.eclipse.org/legal/termsofuse.php"
      identifier = "terms-of-use"
      parent = "eclipse"
      weight = 3
    [[footer]]
      name = "Copyright"
      url = "https://www.eclipse.org/legal/copyright.php"
      identifier = "copyright"
      parent = "eclipse"
      weight = 4
    [[footer]]
      name = "Legal"
      url = "https://www.eclipse.org/legal"
      identifier = "legal"
      parent = "eclipse"
      weight = 5


[[docs]]
  name = "Getting Started"
  identifier = "getting_started"
  url = "/docs/getting_started/"
  weight = 10
  post = "Download and installation."
[[docs]]
  name = "Visualization"
  identifier = "visualization"
  url = "/docs/visualization/"
  weight = 30
  post = "Visualize and evaluate simulation results."
[[docs]]
  name = "Simulators"
  identifier = "simulators"
  url = "/docs/simulators/"
  weight = 40
  post = "Configure external and integrated simulators."
[[docs]]
  name = "Scenarios"
  identifier = "scenarios"
  url = "/docs/scenarios/"
  weight = 50
  post = "Build your own simulation scenarios."
[[docs]]
  name = "Developing Applications"
  identifier = "develop_applications"
  url = "/docs/develop_applications/"
  weight = 60
  post = "Develop applications for the Application Simulator."
[[docs]]
  name = "MOSAIC Configuration"
  identifier = "mosaic_configuration"
  url = "/docs/mosaic_configuration/"
  weight = 70
  post = "Complete documentation of configuration files."
[[docs]]
  name = "Extending Eclipse MOSAIC"
  identifier = "extending_mosaic"
  url = "/docs/extending_mosaic/"
  weight = 80
  post = "Extend Eclipse MOSAIC."
[[docs]]
  name = "API Documentation"
  identifier = "api_docs"
  url = "/docs/api_docs/"
  weight = 90
  post = "Technical documentation, such as Javadoc."

[[tutorials]]
  name = "Getting Started"
  identifier = "getting_started"
  url = "/tutorials/getting_started/"
  weight = 1
  post = """
  <img src="getting_started/images/mosaic-intro.png">
  <p><b>What you will learn:</b></p>
  <ul>
    <li>Download and Install Eclipse MOSAIC</li>
    <li>Running and configuring a simulation scenario</li>
    <li>Gather simulation results</li>
  </ul>
  """
[[tutorials]]
  name = "Barnim: Simulation Basics"
  identifier = "barnim_simulation_basics"
  url = "/tutorials/barnim_simulation_basics/"
  weight = 10
  post = """
  <img src="barnim_simulation_basics/images/barnim-map-intro.png">
  <p><b>What you will learn:</b></p>
  <ul>
    <li>Map applications onto entities</li>
    <li>Choosing between simulators</li>
    <li>Configuration of simulation entities</li>
  </ul>
  """
[[tutorials]]
  name = "Barnim: Develop Applications"
  identifier = "barnim_develop_applications"
  url = "/tutorials/barnim_develop_applications/"
  weight = 20
  post = """
  <img src="barnim_simulation_basics/images/barnim-map-intro.png">
  <p><b>What you will learn:</b></p>
  <ul>
    <li>Developing applications</li>
    <li>Sending and receiving V2X messages</li>
    <li>Choosing different route due to weather conditions</li>
  </ul>
  """
  [[tutorials]]
  name = "Create a new Scenario"
  identifier = "create_new_scenario"
  url = "/tutorials/create_new_scenario/"
  weight = 25
  post = """
  <img src="create_new_scenario/images/create-new-intro.png">
  <p><b>What you will learn:</b></p>
  <ul>
    <li>Create a new scenario</li>
    <li>How to use scenario-convert</li>
    <li>Cleaning map-data before generating the simulation map</li>
    <li>Import routes into your scenario</li>
  </ul>
  """
[[tutorials]]
  name = "Tiergarten: Communication"
  identifier = "tiergarten_communication"
  url = "/tutorials/tiergarten_communication/"
  weight = 30
  post = """
  <img src="tiergarten_communication/images/tiergarten-intro.png">
  <p><b>What you will learn:</b></p>
  <ul>
    <li>Detailed mapping configuration</li>
    <li>Communication between vehicles</li>
    <li>Intra-vehicle application communication</li>
    <li>Event processing within vehicles</li>
  </ul>
  """
[[tutorials]]
  name = "Tiergarten: Traffic Lights"
  identifier = "tiergarten_traffic_lights"
  url = "/tutorials/tiergarten_traffic_lights/"
  weight = 40
  post = """
  <img src="tiergarten_traffic_lights/images/trafficlights-intro.png">
  <p><b>What you will learn:</b></p>
  <ul>
    <li>Adding traffic lights to your scenario</li>
    <li>Mapping applications onto traffic lights</li>
    <li>Working with traffic lights in applications</li>
  </ul>"""
[[tutorials]]
  name = "Integrate SUMO scenarios"
  identifier = "integrate_existing_sumo_scenarios"
  url = "/tutorials/integrate_existing_sumo_scenarios"
  weight = 50
  post = """
  <img src="integrate_existing_sumo_scenarios/images/integrate_existing_sumo_scenarios-intro.png">
  <p><b>What you will learn:</b></p>
  <ul>
    <li>Integrate existing SUMO scenarios with MOSAIC</li>
    <li>Utilize different transport modalities in MOSAIC</li>
  </ul>"""
[[tutorials]]
  name = "LuST"
  identifier = "lust"
  url = "/tutorials/lust/"
  weight = 60
  post = """
  <img src="lust/images/lust-intro.png">
  <p><b>What you will learn:</b></p>
  <ul>
    <li>Integration of existing SUMO scenarios into Eclipse MOSAIC</li>
    <li>Simulate huge traffic amounts</li>
  </ul>"""
[[tutorials]]
  name = "Traffic Management"
  identifier = "traffic_management"
  url = "/tutorials/traffic_management/"
  weight = 70
  post = """
  <img src="traffic_management/images/highway-overview-intro.png">
  <p><b>What you will learn:</b></p>
   <ul>
     <li>Use road detectors to measure traffic</li>
     <li>Change road properties, e.g. close lanes.</li>
     <li>Modelling TMC functions with applications</li>
   </ul>"""
[[tutorials]]
  name = "Example Applications"
  identifier = "additional_examples"
  url = "/tutorials/additional_examples/"
  weight = 80
  post = """
  <img src="additional_examples/images/examples-intro.png">
  <p><b>Here we provide a collection of example applications including the following aspects:</b></p>
  <ul>
   <li>Event Processing</li>
   <li>V2X Communication</li>
   <li>Application Configuration</li>
   <li>... and more</li>
 </ul>
  """

